In [2]:
import numpy as np
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [3]:
sample_array.dtype

dtype('int64')

In [7]:
ones=np.ones((2,5))

In [8]:
ones.dtype

dtype('float64')

In [9]:
type(ones)

numpy.ndarray

In [10]:
zeros= np.zeros(5)

In [11]:
zeros

array([0., 0., 0., 0., 0.])

In [12]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [14]:
random_array= np.random.randint(0,10,size=(3,5))

In [15]:
random_array

array([[2, 6, 8, 3, 1],
       [0, 2, 9, 4, 8],
       [7, 3, 8, 2, 0]])

In [16]:
random_array.size

15

In [17]:
random_array.shape

(3, 5)

In [20]:
np.random.random((5,3))

array([[0.00695309, 0.4403935 , 0.57566002],
       [0.93078239, 0.230393  , 0.64378934],
       [0.58890645, 0.25966533, 0.30997904],
       [0.07567807, 0.41373088, 0.75527031],
       [0.38593033, 0.39231672, 0.48920777]])

## Veiwing arrays and matrices


In [26]:
a1=np.unique(random_array)

In [28]:
a1[0]

0

In [29]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[1, 1, 8, 3, 6],
         [6, 7, 3, 3, 0],
         [2, 7, 4, 9, 4],
         [1, 3, 3, 4, 6]],

        [[7, 5, 5, 5, 8],
         [9, 1, 1, 7, 4],
         [9, 8, 1, 5, 2],
         [0, 9, 8, 3, 7]],

        [[5, 2, 8, 8, 1],
         [0, 4, 1, 3, 3],
         [3, 7, 9, 6, 3],
         [6, 1, 9, 8, 7]]],


       [[[1, 4, 9, 7, 1],
         [4, 3, 3, 4, 6],
         [1, 1, 2, 5, 1],
         [3, 7, 1, 5, 6]],

        [[5, 6, 1, 1, 1],
         [8, 2, 5, 5, 9],
         [8, 7, 0, 8, 7],
         [0, 3, 5, 2, 5]],

        [[9, 8, 9, 0, 9],
         [7, 4, 1, 4, 7],
         [2, 7, 9, 3, 3],
         [6, 8, 2, 4, 2]]]])

In [31]:
a4.shape

(2, 3, 4, 5)

In [32]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10, size= (5,3))

In [33]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [34]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [35]:
mat1.shape , mat2.shape

((5, 3), (5, 3))

In [36]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [37]:
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [40]:
mat1= mat1.T

In [41]:
np.dot(mat1,mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [42]:
np.random.seed(0)
sales_amounts= np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [47]:
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index=['m','t','w','thurs','friday'], columns=['almond bter','peanut bter','cb'])
weekly_sales


                                                  
                                                  

almond bter  peanut bter  cb
m                12           15   0
t                 3            3   7
w                 9           19  18
thurs             4            6  12
friday            1            6   7

In [48]:
prices= np.array([10,2,12])
prices

array([10,  2, 12])

In [51]:
butter_prices=pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=['almond bter','peanut bter','cb'])
butter_prices

almond bter  peanut bter  cb
Price           10            2  12

In [55]:
prices.shape

(3,)

In [54]:
sales_amounts.shape

(5, 3)

In [56]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([150, 120, 344, 196, 106])

In [57]:
butter_prices

almond bter  peanut bter  cb
Price           10            2  12

In [58]:
weekly_sales

almond bter  peanut bter  cb
m                12           15   0
t                 3            3   7
w                 9           19  18
thurs             4            6  12
friday            1            6   7

In [61]:
daily_sales=butter_prices.dot(weekly_sales.T)
daily_sales.shape

(1, 5)

In [60]:
weekly_sales

almond bter  peanut bter  cb
m                12           15   0
t                 3            3   7
w                 9           19  18
thurs             4            6  12
friday            1            6   7

In [62]:
weekly_sales["Total ($)"] = daily_sales
weekly_sales

ValueError: Cannot set a DataFrame with multiple columns to the single column Total ($)